spring.application.name=aee-backend

# JWT
api.security.token.secret=${JWT_SECRET:super-secret-key}

# PostgreSQL
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/aee}
spring.datasource.username=${DATABASE_USERNAME:aee}
spring.datasource.password=${DATABASE_PASSWORD:aee123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# MinIO
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin123}
minio.bucket=${MINIO_BUCKET:aee-documentos}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
